import { createServer } from 'vite';
import { chromium } from 'playwright';
const server = await createServer({ server: { port: 5196 }, logLevel: 'error' });
await server.listen();
const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist', '--autoplay-policy=no-user-gesture-required'] });
const page = await browser.newPage({ viewport: { width: Number(process.argv[3] || 1100), height: Number(process.argv[4] || 680) } });
await page.goto(`http://localhost:${server.config.server.port}/?fixeddt=1`);
await page.waitForSelector('.screen.warning:not(.hidden) button', { timeout: 180000 });
await page.click('.screen.warning button');
await page.waitForSelector('.screen.menu:not(.hidden) .btn', { timeout: 180000 });
await page.mouse.move(5, 5);
const f = await page.evaluate(() => window.__frames);
await page.waitForFunction((n) => window.__frames > n + 12, f, { timeout: 120000 });
await page.screenshot({ path: process.argv[2] || 'screenshots/m_menu.png' });
await browser.close();
await server.close();
